# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.horizontalLayout.addWidget(self.btn_gen_keys)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.verticalLayout_2.addWidget(self.txt_plain_text)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_encrypt = QtWidgets.QPushButton(self.groupBox)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.horizontalLayout_2.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.groupBox)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.horizontalLayout_2.addWidget(self.btn_decrypt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.verticalLayout_2.addWidget(self.txt_cipher_text)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.txt_info = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txt_info.setObjectName("txt_info")
        self.verticalLayout_3.addWidget(self.txt_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_sign = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_sign.setObjectName("btn_sign")
        self.horizontalLayout_3.addWidget(self.btn_sign)
        self.btn_verify = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_verify.setObjectName("btn_verify")
        self.horizontalLayout_3.addWidget(self.btn_verify)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.txt_sign = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txt_sign.setObjectName("txt_sign")
        self.verticalLayout_3.addWidget(self.txt_sign)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Encryption/Decryption"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))
        self.groupBox.setTitle(_translate("MainWindow", "Encryption/Decryption"))
        self.label.setText(_translate("MainWindow", "Plain Text:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label_2.setText(_translate("MainWindow", "Cipher Text:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Digital Signature"))
        self.label_3.setText(_translate("MainWindow", "Message:"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.label_4.setText(_translate("MainWindow", "Signature:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
